name: app_map_tracking
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
isar_version: &isar_version 3.1.0 # define the version to be used

environment:
  sdk: ^3.5.0

dependencies:
  connectivity_plus: ^6.1.4
  flutter:
    sdk: flutter  
  flutter_riverpod: ^2.6.1
  geolocator: ^10.1.0
  go_router: ^15.1.1
  http: ^1.4.0
  maplibre_gl: ^0.21.0 
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  android_alarm_manager_plus: ^4.0.7
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dependency_overrides:
  geolocator_android: 4.6.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/maplibre/
    - assets/images/
